version: "3.4"

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi5
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIROMENT=Development
      - ConnectionString=Server=sql.bsite.net\MSSQL2016;Database=shelteranimal_;User ID=shelteranimal_;Password=password_123;TrustServerCertificate=True;
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=password_123"
      - "ACCEPT_EULA=Y"
    container_name: mssql-5
    ports:
      - "1555:1433"